@extends('layouts.mail')


@section('header')

<h1 style="color:white"> Hello {{ $name }},</h1>
@endsection

@section('body')
<p style="color: rgb(31,41,55); padding:10px " > Here is your autogenerated password : {{ $msgContent }} <br/>

Please make sure you login and reset it to your liking.

</p>
@endsection



@section('footer')
<p style="color: white; padding:10px ;">CarDrive Social Login Mail</p>
@endsection


