@extends('layouts.mail')


@section('header')

<h1 style="color:white"> Hello {{ $name ?? " " }},</h1>
@endsection

@section('body')
<p style="color: rgb(31,41,55);" > Here is your autogenerated password : {{ $pass ?? " "}} <br/>

Please make sure you login and reset it to your liking.

</p>
@endsection



@section('footer')
<p style="color: white;font-weight:bold">{{ env('APP_NAME')}} Social Login Mail</p>
@endsection


